/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obilet;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Emirhan Guney
 */
public class biletalma extends javax.swing.JFrame {

    /**
     * Creates new form biletalma
     */
    public biletalma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("5");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setText("6");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("14");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton5.setText("9");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("13");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("10");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("25");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setText("29");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("26");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("22");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("17");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("30");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("21");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("18");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton20.setText("37");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("33");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("38");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("34");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton26.setText("11");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("15");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("12");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setText("27");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("31");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("28");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("24");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setText("19");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setText("32");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setText("3");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setText("23");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setText("7");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setText("4");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setText("20");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.setText("39");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setText("35");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton44.setText("40");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        jButton45.setText("36");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        jButton47.setText("8");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        jButton49.setText("16");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obilet/direksiyon1.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setText("Geri");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jButton18)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton2.setBackground(Color.pink);
                    jButton2.setEnabled(false);
                    
                }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton3.setBackground(Color.pink);
                    jButton3.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton5.setBackground(Color.pink);
                    jButton5.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton31.setBackground(Color.pink);
                    jButton31.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       
        setVisible(false);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton4.setBackground(Color.pink);
                    jButton4.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
// Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton35.setBackground(Color.pink);
                    jButton35.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton38.setBackground(Color.pink);
                    jButton38.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton9.setBackground(Color.pink);
                    jButton9.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
      // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton37.setBackground(Color.pink);
                    jButton37.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton47.setBackground(Color.pink);
                    jButton47.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton7.setBackground(Color.pink);
                    jButton7.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
      // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton26.setBackground(Color.pink);
                    jButton26.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton28.setBackground(Color.pink);
                    jButton28.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton6.setBackground(Color.pink);
                    jButton6.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton10.setBackground(Color.pink);
                    jButton10.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton27.setBackground(Color.pink);
                    jButton27.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton49.setBackground(Color.pink);
                    jButton49.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton14.setBackground(Color.pink);
                    jButton14.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton17.setBackground(Color.pink);
                    jButton17.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton33.setBackground(Color.pink);
                    jButton33.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton39.setBackground(Color.pink);
                    jButton39.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton16.setBackground(Color.pink);
                    jButton16.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton13.setBackground(Color.pink);
                    jButton13.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton36.setBackground(Color.pink);
                    jButton36.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton32.setBackground(Color.pink);
                    jButton32.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton8.setBackground(Color.pink);
                    jButton8.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton12.setBackground(Color.pink);
                    jButton12.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton29.setBackground(Color.pink);
                    jButton29.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton11.setBackground(Color.pink);
                    jButton11.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton15.setBackground(Color.pink);
                    jButton15.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton30.setBackground(Color.pink);
                    jButton30.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton34.setBackground(Color.pink);
                    jButton34.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton21.setBackground(Color.pink);
                    jButton21.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton23.setBackground(Color.pink);
                    jButton23.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton41.setBackground(Color.pink);
                    jButton41.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton45.setBackground(Color.pink);
                    jButton45.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton20.setBackground(Color.pink);
                    jButton20.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton22.setBackground(Color.pink);
                    jButton22.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton40.setBackground(Color.pink);
                    jButton40.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
 // Ad ve Soyad girişi için JTextField'lar
                JTextField adTextField = new JTextField();
                JTextField soyadTextField = new JTextField();

                // Label oluştur ve içeriğini ayarla
                
                JLabel ucretLabel = new JLabel("BILET BEDELI:1000");

                // Giriş ekranını oluştur
                Object[] message = {
                    "Ad:", adTextField,
                    "Soyad:", soyadTextField,
                    ucretLabel
                };

                int option = JOptionPane.showConfirmDialog(null, message, "Ad ve Soyad Giriniz", JOptionPane.OK_CANCEL_OPTION);

                if (option == JOptionPane.OK_OPTION) {
               

                    // İşlem tamamlandı mesajını göster
                    JOptionPane.showMessageDialog(null, "İŞLEMİNİZ TAMAMLANMIŞTIR!");
                    jButton44.setBackground(Color.pink);
                    jButton44.setEnabled(false);
                    
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton44ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biletalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biletalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biletalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biletalma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biletalma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
